python: 3.7

os:
  - linux

script:
  - pip install -r requirements.txt
  - python -m pytest tests/test_grammars.py

notifications:
  email:
    recipients:
      - estetus+travis-ci@gmail.com
    on_success: change
    on_failure: always
